name = "mintmorsel-websocket"
main = "src/index.ts"
compatibility_date = "2025-03-28"

[durable_objects]
bindings = [
  { name = "ORDER_MANAGER", class_name = "OrderManager" }
]

[[migrations]]
tag = "v1"
new_classes = ["OrderManager"]
